[package]
name = "glox"
version = "0.1.0"
authors = ["95th <vargwin@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
num-derive = "0.3"
log = { version = "0.4.8", features = ["release_max_level_off"] }
env_logger = "0.7.1"